application:
  title: Car Lease App 2.0
  version: 2.0.0

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: car_leas_app
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    initialization-mode: always